import os

class Config:
    OPENSTACK_AUTH_URL = os.getenv("OS_AUTH_URL")
    OPENSTACK_USERNAME = os.getenv("OS_USERNAME")
    OPENSTACK_PASSWORD = os.getenv("OS_PASSWORD")
    OPENSTACK_PROJECT_NAME = os.getenv("OS_PROJECT_NAME")
    OPENSTACK_USER_DOMAIN_NAME = os.getenv("OS_USER_DOMAIN_NAME")
    OPENSTACK_PROJECT_DOMAIN_NAME = os.getenv("OS_PROJECT_DOMAIN_NAME")